### ISSUE TITLE
Multiple tag support

### ISSUE THREAD

**Issue by jpoehnelt** [orbit-love/community-js-stackoverflow-orbit#1]
I didn't see this documented. Would be a nice feature to have.

**Comment by phazonoverload** [comment]
Heya! You’re right - it currently isn’t supported. 

My initial thinking was to have users call the method twice - once per tag. This allows more fine-grained control such as different time periods per tag. 

Would a built-in support for >1 tag be useful? If so it’s certainly something I can look at next week.

**Comment by jpoehnelt** [comment]
GitHub action matrix could be documented as way around this instead.

```yaml
name: Orbit.love
on:
  schedule:
    - cron: "*/30 * * * *"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - foo
        - bar
        - baz
    steps:
      - run: npx @orbit-love/stackoverflow --questions --hours=1 --tag "${{ matrix.tag }}"
        env:
          STACK_APPS_KEY: ${{ secrets.STACK_APPS_KEY}}
          ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY}}
          ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID}}
```

This should work, although I'm running into a different issue #2.
